[package]
name = "logging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
log4rs = "1.2.0"
serde_yaml = "0.9.22"
signal-hook = "0.3.15"
