version: '3'
services:
  my_http_server:
    command: [ "./my_http_server", "-t", "10" ]
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"   # AMQP port
    networks:
      - test_network

  test_runner:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile.testrunner
    depends_on:
      - my_http_server
    networks:
      - test_network
networks:
  test_network:
    driver: bridge