[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
tokio = { version = "1.28.2", features = ["full"] }
env_logger = "0.10.0"
log = "0.4.19"
